# Default values for mlflow-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

git:
  # @param {boolean} [unsupportedCapabilities] UnsupportedCapabilities enable Go-Git transport.UnsupportedCapabilities Azure DevOps requires capabilities multi_ack / multi_ack_detailed, which are not fully implemented in go-git library and by default are included in transport.UnsupportedCapabilities.
  unsupportedCapabilities: true
  # @param {enum{Delete,Orphan}} [deletionPolicy] DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
  deletionPolicy: Orphan
  # @param {boolean} [insecure] Insecure is useful with hand made SSL certs
  insecure: true
  # @param {object} [fromRepo] Parameters section for Git repository used as template for the application skeleton
  fromRepo:
    # @param {string} [scmUrl] (schema+host e.g. https://github.com) for the target Git repository
    scmUrl: https://github.com
    # @param {string} [org] Organization/group/subgroup for the target Git repository
    org: krateoplatformops
    # @param {string} [name] Name for the target Git repository
    name: krateo-v2-template-mlflow
    # @param {string} [branch] Branch of Git repository used as template for the application skeleton
    branch: main
    # @param {enum{skeleton/train_diabetes,skeleton/train_diabetes-v2}} [path] Path of Git repository used as template for the application skeleton
    path: skeleton/train_diabetes
    # @param {object} [credentials] References to the secrets that contain the credentials required to clone the repository (in case of private ones)
    credentials:
      # @param {enum{basic,bearer}} [authMethod] AuthMethod defines the authentication mode. One of 'basic' or 'bearer'
      authMethod: basic
      # @param {object} [secretRef] Reference details about the secret where the credentials are stored
      secretRef:
        # @param {string} [namespace] Namespace of the secret where the credentials are stored
        namespace: mlflow-system
        # @param {string} [name] Name of the secret where the credentials are stored
        name: gh-token
        # @param {string} [key] Key of the secret to use
        key: token
  # @param {object} toRepo Parameters section for Git repository that will be created by Krateo
  toRepo:
    # @param {string} [scmUrl] (schema+host e.g. https://github.com) for the target Git repository
    scmUrl: https://github.com
    # @param {string} [org] Organization/group/subgroup for the target Git repository
    org: generic-provider-testing
    # @param {string} name Name for the target Git repository
    name: mlflow-test-run
    # @param {string} [branch] Branch for the target Git repository
    branch: main
    # @param {string} [path] Path where the template will be placed
    path: /
    # @param {object} [credentials] References to the secrets that contain the credentials required to push the content the repository (in case of private ones)
    credentials:
      # @param {enum{basic,bearer}} [authMethod] AuthMethod defines the authentication mode. One of 'basic' or 'bearer'
      authMethod: basic
      # @param {object} [secretRef] Reference details about the secret where the credentials are stored
      secretRef:
        # @param {string} [namespace] Namespace of the secret where the credentials are stored
        namespace: mlflow-system
        # @param {string} [name] Name of the secret where the credentials are stored
        name: gh-token
        # @param {string} [key] Key of the secret to use
        key: token
    # @param {string} [apiUrl] URL to use for API
    apiUrl: https://api.github.com
    # @param {boolean} [private] Whether the repository is private
    private: false
    # @param {boolean} [initialize] Whether the repository must be initialized
    initialize: true
    # @param {enum{Delete,Orphan}} [deletionPolicy] DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
    deletionPolicy: Delete

mlflow:
  experiment:
    name: diabetes-training-exp1
  credentials:
    secretRef:
      namespace: mlflow-system
      name: azure-token
      key: access_token