apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow-app.fullname" . }}-replace-values
  labels:
    {{- include "mlflow-app.labels" . | nindent 4 }}
data:
  values: |
    { "organizationName": "{{ .Values.git.toRepo.org }}",
      "repositoryName": "{{ .Values.mlflow.experiment.name }}",
    }