apiVersion: mlflow.krateo.io/v1alpha1
kind: Experiment
metadata:
  name: {{ .Values.mlflow.experiment.name }}-experiment
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.mlflow.experiment.name }}
  authenticationRefs:
    bearerAuthRef: {{ include "mlflow-app.fullname" . }}-mlflow-auth-ref