apiVersion: github.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ include "mlflow-app.fullname" . }}-repo
  labels:
    {{- include "mlflow-app.labels" . | nindent 4 }}
spec:
  org: {{ .Values.git.toRepo.org }}
  name: {{ .Values.git.toRepo.name }}
  private: {{ .Values.git.toRepo.private }}
  auto_init: {{ .Values.git.toRepo.initialize }}
  authenticationRefs:
    bearerAuthRef: {{ include "mlflow-app.fullname" . }}-auth-ref