{{- $exp := lookup "mlflow.krateo.io/v1alpha1" "Experiment" .Release.Namespace (print (include "mlflow-app.fullname" .) "-experiment") -}}
{{- if and $exp $exp.status $exp.status.experiment_id }}

kind: MlflowRuns
apiVersion: composition.krateo.io/v0-0-1
metadata:
  name: {{ include "mlflow-app.fullname" . }}-runs-composition
spec:
  repo:
    owner: {{ .Values.git.toRepo.org }}
    name: {{ .Values.git.toRepo.name }}
    workflow_id: "run.yaml"
    ref: {{ .Values.git.toRepo.branch }}
  experiment: 
    experiment_name: {{ .Values.mlflow.experiment.name }}
    experiment_id: $exp.status.experiment_id 
  run_name: mlflow-run-composition-{{ randAlphaNum 5 | lower }}
{{- end }}
