kind: MlflowRuns
apiVersion: composition.krateo.io/v0-0-3
metadata:
  name: {{ printf "%s-runs-comp" (include "mlflow-app.fullname" .) | trunc 53 | trimSuffix "-" }}
spec:
  repo:
    owner: {{ .Values.git.toRepo.org }}
    workflow_id: "run.yaml"
    ref: {{ .Values.git.toRepo.branch }}
  mlflow:
    experiment: 
      name: {{ .Values.mlflow.experiment.name }}
    credentials:
      secretRef:
        namespace: {{ .Values.mlflow.credentialReferences.secretReference.namespace }}
        name: {{ .Values.mlflow.credentialReferences.secretReference.name }}
        key: {{ .Values.mlflow.credentialReferences.secretReference.key }}
    run:
      name: mlflow-run-composition-{{ randAlphaNum 5 | lower }}
      alpha: "0.5"
      metrics:
        - name: "mse"