name: AzureML Train Diabetes

on:
  workflow_dispatch:
    inputs:
      alpha:
        description: 'Alpha value for Ridge regression'
        required: true
        default: '0.03'
      experiment_name:
        description: 'Name of the experiment'
        required: true
        default: 'diabetes-training'
      run_id:
        description: 'Run ID'
        required: true
        default: '0'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run train_diabetes.py
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}
      run: |
        python run.py --alpha ${{ github.event.inputs.alpha }} --experiment_name ${{ github.event.inputs.experiment_name }} --run_id ${{ github.event.inputs.run_id }}